# Generated by Django 6.0.5 on 2026-05-31 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True)),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=70, unique=True)),
            ],
            options={
                'verbose_name': 'plataforma',
                'verbose_name_plural': 'plataformas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivery_type', models.CharField(choices=[('automatic_key', 'Clave digital (entrega automática)'), ('shared_account', 'Cuenta compartida (entrega guiada)'), ('topup', 'Recarga / gift card (semiautomática)'), ('manual', 'Entrega manual (gestionada por admin)')], help_text='Determina cómo se entrega el producto tras el pago.', max_length=20)),
                ('manual_stock', models.PositiveIntegerField(default=0, help_text='Stock para productos topup/manual. Ignorado en claves digitales.')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.platform')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['delivery_type'], name='catalog_pro_deliver_3d65ef_idx'), models.Index(fields=['is_active'], name='catalog_pro_is_acti_14fc6b_idx')],
            },
        ),
    ]
