# Generated by Django 6.0.5 on 2026-05-31 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('success', 'Entregado'), ('failed', 'Fallido'), ('awaiting_admin', 'Esperando acción del admin')], default='pending', max_length=16)),
                ('encrypted_payload', models.TextField(blank=True)),
                ('public_message', models.CharField(blank=True, max_length=255)),
                ('error_detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_records', to='orders.orderitem')),
            ],
            options={
                'verbose_name': 'registro de entrega',
                'verbose_name_plural': 'registros de entrega',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='delivery_de_status_ae3508_idx')],
            },
        ),
        migrations.CreateModel(
            name='DigitalKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_value', models.TextField()),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Reservada'), ('delivered', 'Entregada')], default='available', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_keys', to='orders.orderitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='catalog.product')),
            ],
            options={
                'verbose_name': 'clave digital',
                'verbose_name_plural': 'claves digitales',
                'indexes': [models.Index(fields=['product', 'status'], name='delivery_di_product_84c51a_idx')],
            },
        ),
    ]
