# Generated by Django 6.0.5 on 2026-05-31 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalkey',
            name='reserved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
