# Generated by Django 6.0.5 on 2026-05-31 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_digitalkey_reserved_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalkey',
            name='status',
            field=models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Reservada'), ('delivered', 'Entregada'), ('revoked', 'Revocada')], default='available', max_length=12),
        ),
    ]
